language: node_js
node_js:
  - 6
env:
  - CI=false
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "CIIUKV9OZywXD8GuNnxuheOqOegm5IA336KD8AjKxvAaJxLh4SuIMDBto31/Q036jnfkHcKIy/PPoknZEq7oyUyxVinbJQ1EqZ9CfQBBEN46Zw1NEJ0rSp8Kf+5Zsawr9m0MI3CWWzhYCH83JRYivwxkQ2qo23UL+pj2McF2xt9eFC1pDHxse6KHlBbqtvK9Spcc+snECf7Vdxy4pWMUNdejFQqKLeuo0jIwCrLTI527/Jn402J3lCX593bZSCUbCdFIT94Ecn3pSlUgmZkiMmRt7Cr7C+hzhHefKqTJ6p01mupbPxDothEFAA6kv9PfZ9pNWIuoISTBVLuUDQrrO4w7QEsie5/CgJuxf4G5AOdciHRSP+FZiysQusl+sTVmJvNIPxsAPHqjZa2UAkDHFZXbTAnYfQ1Pj8qFxVwxxwNT+k3pJYeSafgheDPoZKMvUZfg70TUlpp43IhBnpgvkaeY0zAHXd2hyD2dbBXSrUbLZuZid+POFrFj+QkxRCmxhRL+cGuvpJ8NC9Y0f55E2wU5B6RWp7vVlGCt//j2WfNLSnIbugWjv2lRw8LaIkBoNBVd0FE9PT+Bv6FHSLZkYED8/RYFoNQBmLg7P0NejhjDu8fbtOm+UrzNxFE2lhzWXRl15FhibOeNfi4APoRpG4Wzv0ETOnnwvE2QIbszNAM="